### ISSUE TITLE
How to open .obj file with meshlab in command tool?

### ISSUE THREAD

**Issue by yanhao-li** [danielepanozzo/cg#1]
In the assignment 1, Ex.1. The instruction saying

> Once you complete the assignment, you should be able to open the resulting file with Meshlab:
> `meshlab output.obj`

Can I ask how to install the meshlab cli? I can't find much information related on google.

**Comment by danielepanozzo** [comment]
Hi,  you can download meshlab here: https://www.meshlab.net/#download

There is no need to launch it from the command line, you can open the file directly from the UI.

**Comment by yanhao-li** [comment]
gotcha, thanks!
