### ISSUE TITLE
Assignment 1 - Cross product?

### ISSUE THREAD

**Issue by DebraChait** [danielepanozzo/cg#10]
I am working on assignment 1, and on the Wikipedia page for Graham Scan, it said one could determine whether a point would be a left turn or a right turn from the current line by taking the cross product of the lines formed and observing the sign. First of all, is this correct? If it is, what is the intuition behind this, and is this related to using the determinant? I would like to use the determinant, but I am not sure how to take the determinant in reference to a line rather than just taking the determinant between two points.

**Comment by danielepanozzo** [comment]
This was explained in the class yesterday, in case it is still unclear please reopen this issue.
