### ISSUE TITLE
Assignment 1 Meshlab

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#12]
I downloaded Meshlab, and I am trying to use it to check the output of assignment 1.  Unfortunately, it looks like it doesn't work as a terminal command, but only works through the GUI for me.  I have a Mac computer.  Is there an extra step necessary to make it work through the terminal command?  Alternatively, how do you open up a .obj file properly through the GUI?

**Comment by arvigj** [comment]
Meshlab is a GUI application. You can either download the binary on their website or install via Homebrew package manager (`brew install meshlab` I believe, but calling meshlab on the terminal will open the GUI application). To import obj, go to File -> Import Mesh.

**Comment by jessberg** [comment]
Thanks, that worked!
