### ISSUE TITLE
What exactly have to be written?

### ISSUE THREAD

**Issue by khandu-utkarsh** [danielepanozzo/cg#13]
Do we need to describe what each function is doing and why?
For example: Why a determinant is computed and how to compute it? Or why sorting of points is done, what is the comparing function that is used? etc.

Or should it be like a pseudo code of the implementation describing in a detailed manner what is done by each of the lines of a block of code?

How much deeper do we have to delve when writing the description about the implementation of an algorithm?

Is there an existing template that can be used as reference?

**Comment by khandu-utkarsh** [comment]
@danielepanozzo  @arvigj  Can we submit the zip files containing all other the source code and report

**Comment by danielepanozzo** [comment]
Hi,

it does not need to detail the code at a function level. It is sufficient to provide a high-level description of the algorithm that you implemented and attach images/screenshots that show the results you obtained. Yes you should create a single zip file that contains both the code and the report, you can find the instructions here: https://github.com/danielepanozzo/cg/blob/master/RULES.md

**Comment by khandu-utkarsh** [comment]
Got it!
Thanks, Professor!
