### ISSUE TITLE
Assignment 2 Inquiry

### ISSUE THREAD

**Issue by allenZhangPersonal** [danielepanozzo/cg#19]
For Assignment 2 I have the following questions.

1. For Ex.1: Basic Ray Tracing, are we only adding code to raytrace_parallelogram() (for orthographic view) and raytrace_perspective() (for perspective view) for this implementation?
2.  For comparing the difference in the result for a sphere and a parallelogram, can we implement a scene with both of them and compare their results both in shading as well as their difference in orthographic and perspective view?

3. For Ex2. Shading, are we only playing around with the coefficients of the ambient, specular, and diffuse shading? Additionally, do we not clamp to zero for each shading rather than clamping after adding them together?
4. What does it mean by adding RGB components instead of the current grey-scale one? Do we basically manipulate the color output by multiplying it with a scalar when we write the matrix to png?

Thank you.

best regards,
Chen Song Zhang

**Comment by danielepanozzo** [comment]
1. You will also have to change the code for ray to sphere intersection, as it will not work for perspective projection.
2. Yes
3. Yes. You should clamp the individual components of the shading equation, not clamp the sum.
4. You will have to render 3 images, one for R, one for G, and one for B. Accordingly, the color of the light and the material properties will have values for R,G, and B.

**Comment by allenZhangPersonal** [comment]
I am a bit confused on rendering the three images for R, G, and B. Are we saying that the color of the light will have R, G, and B values and the material itself will also have R, G, and B values? Therefore, our final rendered image will contain R, G, and B values? Then, in our code, do we need to randomly initialize the color of the light, and randomly initialize the color of the actual sphere to compute the three colors for our final output image?

Thank you.

**Comment by danielepanozzo** [comment]
Yes that's correct. Instead of randomizing, you can simply decide and fix the color of the sphere. For the lights, it is easier if you keep them white (i.e. 1 for R,G, and B).

**Comment by allenZhangPersonal** [comment]
Understood, thank you very much!

**Comment by DebraChait** [comment]
To clarify: there are currently no TODOs regarding ray to sphere perspective projection, nor are there instructions about it in the assignment README. Are we supposed to add ray to sphere perspective projection?

**Comment by arvigj** [comment]
This is required in the `raytrace_shading` function part of the assignment.

**Comment by khandu-utkarsh** [comment]
What are the values of the coefficients and phong exponent we have to take for shading part? Is there any table available for it?

**Comment by danielepanozzo** [comment]
For the phong exponent there is a table in the top right of the slide explaining the specular shading. The other coefficient in the formula it is simply the (specular) color of the object, you can pick any color you like for the assignment.

**Comment by allenZhangPersonal** [comment]
> This is required in the `raytrace_shading` function part of the assignment.

Does this mean that for shading, we require a perspective view of the sphere? I don't see that in the code or the readme. Just making certain.

**Comment by khandu-utkarsh** [comment]
> * You will also have to change the code for the ray to sphere intersection, as it will not work for perspective projection.
> * Yes
> * Yes. You should clamp the individual components of the shading equation, not clamp the sum.
> * You will have to render 3 images, one for R, one for G, and one for B. Accordingly, the color of the light and the material properties will have values for R, G, and B.

@danielepanozzo @arvigj 
I got confused by the last point
What do you mean we you say that render 3 images? Is it that we need to create 3 PNGs one for each color for the exact same scene or is it that we only need to create one PNG while doing shading calculations for all three different colors.

**Comment by danielepanozzo** [comment]
Sorry for the confusion let me try to clarify. You will have to create 3 matrices, one for R, one for G, and one for B, and then save them as a single PNG with 4 channels (RGBA).

**Comment by khandu-utkarsh** [comment]
I get it now!
Thanks!
