### ISSUE TITLE
x_displacement and y_displacement

### ISSUE THREAD

**Issue by yanhao-li** [danielepanozzo/cg#2]
Hi,

I have difficulties for understanding what `x_displacement(2.0/C.cols(),0,0)` and `y_displacement(0,-2.0/C.rows(),0)` does in the [code](https://github.com/danielepanozzo/cg/blob/master/Assignment_2/src/main.cpp#L26-L27), specifically where the `2.0` and `-2.0` come from?

and I saw this formula on the textbook, what's the `l, r, t, b` in our project and why there has `0.5`?
![image](https://user-images.githubusercontent.com/12378652/94688649-e3649a00-02fb-11eb-9385-1f4404118cc9.png)

Can anyone please help me? thank you!

**Comment by danielepanozzo** [comment]
2 is the size of the image. x_displacement and y_displacement are used within the pair of for loops to compute the position of the pixels of the image.

**Comment by yanhao-li** [comment]
@danielepanozzo Isn't the size of image 800px * 800px? Where do we declare the size to be 2?

**Comment by danielepanozzo** [comment]
The image has 800x800 pixels. In the scene, the "sensor" of the camera is represented by a rectangle, which in the provided code has size 2. If you change the number of pixels, you will get an image of the same scene that is more or less detailed. If you change the size of the rectangle, you will get an effect similar to changing lens in a camera: a smaller rectangle will correspond to a narrower field of view.

**Comment by yanhao-li** [comment]
Got it now, thank you for the elaboration!
@danielepanozzo
