### ISSUE TITLE
basic raytracing question

### ISSUE THREAD

**Issue by Sanainui** [danielepanozzo/cg#23]
when raytracing a parallelogram, we are instructed to "Compute the normal of that intersection point." in the 4th step. But in the code, there is already a way to compute the norm by calling ray_intersection.normalized(). Should we modify this part? if so, can you give some hints?

**Comment by danielepanozzo** [comment]
The computation of the normal is specific to each primitive --- you will have to implement a function for the sphere and one for the parallelogram. The normal of the parallelogram is a vector perpendicular to the plane that contains it, a suggestion is to find two vectors on that plane, and then use the cross product.

**Comment by Sanainui** [comment]
Cross product depends on the order of two vectors. Does this matter?

**Comment by danielepanozzo** [comment]
Yes it does. Only the "front" part of the parallelogram will be shaded properly. 

Also please make sure that you are clear on the difference between a vector norm (.norm() ) and the normal vector. They are not the same thing.
