### ISSUE TITLE
Problem with prepare_assignments.sh

### ISSUE THREAD

**Issue by oliverzlu** [danielepanozzo/cg#25]
I got the following error while trying to run prepare_assignments.sh (`sh prepare_assignment.sh Assignment_2 Assignment_2/writeup.pdf`)

`prepare_assignments.sh: 9: prepare_assignments.sh: Syntax error: end of file unexpected (expecting "then")`

Is it ok if we just zip the folder with the writeup included and submit that?

**Comment by danielepanozzo** [comment]
Yes that's fine!
