### ISSUE TITLE
Question about Ex.2 Shading 

### ISSUE THREAD

**Issue by yaozcoderepo** [danielepanozzo/cg#26]
For homework 2 ex.2 "shading section", Are we supposed to simulate both orthographic and perspective views with shading for sphere and parallelogram (thus, 4 png files with shading for Ex.2)?

**Comment by danielepanozzo** [comment]
You should show both a sphere and a parallelogram, it is sufficient to show either orthographic or perspective (it does not make a difference as the shading part is independent from the ray generation).

**Comment by DebraChait** [comment]
Is it okay to use the special case of the sphere centered at the origin for the shading section?

**Comment by danielepanozzo** [comment]
Yes

**Comment by HerlinHe** [comment]
But Professor, you didn't mention we need to implement both sphere and parallelogram in the assignment page or code. Some students read the issue a few hours before the due, some students still don't know. Could you please make the requirement a little more precise next time? Thank you very much.

**Comment by danielepanozzo** [comment]
Given the ambiguity, for the shading part it will be sufficient to have either the sphere or the parallelogram. The text was indeed not sufficiently clear.
