### ISSUE TITLE
Distortion in perspective raytracing

### ISSUE THREAD

**Issue by MinervaMint** [danielepanozzo/cg#3]
Hello,

I am trying to generalize the code for raytracing a sphere so that it can work with spheres at any position, but I find that the result I got seems distorted when the sphere is not in the center of the image. The result image seems somewhat oval (as shown below). 
I am wondering whether this is possible, or it should never happen so there are bugs in my code?
![shading](https://user-images.githubusercontent.com/32100098/94971006-e9ad6e80-04d3-11eb-83a2-1f4529fb8705.png)
Thanks in advance.

**Comment by danielepanozzo** [comment]
Hi, yes this is possible depending on the position of the viewer wrt the sensor/image. It is likely that the position of your viewer is misaligned with the center of the image, i.e. the vector connecting the viewer to the center of the image is not perpendicular to the image plane.

**Comment by MinervaMint** [comment]
In my code the image is a square parallel to the xy-plane, covering (-1,1) in x and y with z-value of 1. So I set the viewer to be at `(0,0,2)`. I thought this means my viewer and the image center is aligned. Is this the only possibility of such distortion happening?

**Comment by danielepanozzo** [comment]
I was not clear before: the distortion is proportional to how "off-axis" the center of the sphere is wrt the vector connecting the viewer to the center of the image. Assuming that they are aligned and that in the image above you moved the sphere "up" then the result is correct. You should get a circle which is compressed horizontally, and it is more tall than wide.

**Comment by MinervaMint** [comment]
Ah yes I did move the sphere up a little bit. Thank you! 
Can I also ask that why this would happen? I mean, intuitively I understand, but is there any formal way of explaining it? Also, how is this "distortion" dealt with in real-world applications?

**Comment by danielepanozzo** [comment]
The projective distortion is due to the camera model that we use (pinhole camera), which is an approximation of a real optical system (such as a camera or our eyes). This distortion is part of how we perceive the world, objects that are far away from us are smaller in the image.

**Comment by MinervaMint** [comment]
Thank you for explanation!
