### ISSUE TITLE
Assignment 3 Refraction Inquiry

### ISSUE THREAD

**Issue by allenZhangPersonal** [danielepanozzo/cg#30]
Good evening,

I am just wondering if there are papers or instructions on how to calculate the color of the refracted ray. For example, what is the total internal reflection, and what is considered a "small" incident direction (near 0 degrees to -norm)? Should we account for how many bounces are left, i.e. will refraction also be recursive since reflected rays will possibly hit other objects? Additionally, it seems that the refraction index is 1 in the .json file. Does this mean that all spheres have refraction index 1 or is the refraction index 0 for all materials since their "Material" value is 0? I am quite confused about the refraction perspective of this assignment.

**Comment by danielepanozzo** [comment]
There is a detailed pseudocode for handling refractions in the textbook, I recommend to follow that algorithm. If there are still questions let me know.
