### ISSUE TITLE
Do we need reflection and refraction in Assignment 4?

### ISSUE THREAD

**Issue by HerlinHe** [danielepanozzo/cg#31]
Hi professor, I guess your sample pictures are generated without reflection and refraction parts, right? I found if I add reflection and refraction, then the recursions significantly slow down my program. So do I need them for this assignment?

**Comment by danielepanozzo** [comment]
Yes, it is not required to add reflection or refraction for Assignment 4. After you add the acceleration data structures, it should be possible (but not required) to render at least the bunny with these effects enabled.
