### ISSUE TITLE
How to compute scale_x and scale_y in Assignment 3?

### ISSUE THREAD

**Issue by Sanainui** [danielepanozzo/cg#35]
I assume the theta in the problem description is the "field_of_view". How can I get scale_x and scale_y from "field_of_view" and "aspect_ratio"? I tried tan(theta/2) * f to compute h, which I think is scale_x, but this quantity is apparently larger than 1. I also tried to search in the textbook, but nothing was found. In addition, I notice there is a quantity called "LensRadius" in the scene.json. Is this quantity also needed to compute scale_x and scale_y?

**Comment by Huangzizhou** [comment]
What you thought to be `scale_x` is actually `scale_y`, and it doesn't matter if it's larger than 1. The `aspect_ratio` is the width divided by the height, so you can get the `scale_x` using `aspect_ratio` and `scale_y`.
