### ISSUE TITLE
Mysteriously resolved - fatal error: 'wchar.h' file not found

### ISSUE THREAD

**Issue by DebraChait** [danielepanozzo/cg#38]
My project was running normally yesterday, but today I get an error when I run make: fatal error: 'wchar.h' file not found
I have not installed anything or done anything to change header files or anything funky on my laptop. I am running MacOS Big Sur 11.6. What can I do to fix this? I cannot make any progress with this error.

**Comment by DebraChait** [comment]
I have a new error after running git clean -xdf. It now says 
ld: library not found for -lc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
I would really appreciate any help here.

**Comment by DebraChait** [comment]
After deleting both my buildDebug and buildRelease, the issue disappeared. Not sure why this happened, if anyone learns more or runs into the issue feel free to comment here.

**Comment by danielepanozzo** [comment]
That is strange. Could it be that xcode was updating automatically in the background? Apple released an update yesterday. Anyhow glad to hear that this was solved.

**Comment by HerlinHe** [comment]
yeah, I met the same problem too after the update of apple yesterday. And after git clean -xdf, now it runs much slower than before. Now I use 1 hour for bunny without using a tree, but I remember it didn't take so long before the update. And with the accelerating of bvh, it took seconds for both bunny and dragon, but now it takes 20s for bunny and fail to produce dragon. I am very confused about the situation. By the way, I use "DCMAKE_BUILD_TYPE=Release" all the time.

**Comment by HerlinHe** [comment]
Now, it turns back to normal automatically, and I don't know why. Never mind :)
