### ISSUE TITLE
Understanding the pseudocode for reflection and refraction in the textbook

### ISSUE THREAD

**Issue by Sanainui** [danielepanozzo/cg#39]
I am reading page 326 of the textbook (4th edition). I am confused by the notation k_r, k_g, k_b, a_r, a_g, a_b. Could someone please explain?

**Comment by danielepanozzo** [comment]
I am not sure I understand the question. Could you please post a snipped of the formula (I do not have the book with me right now) and clarify what is confusing? The subscripts stand for the different color channels.

**Comment by Sanainui** [comment]
<img width="494" alt="EBD02759-85D3-49A3-8C6C-D483BE25FFBF" src="https://user-images.githubusercontent.com/32924396/139075323-edc93dc8-a23a-45f2-8710-4551893fec7a.png">

<img width="600" alt="C8696C02-F071-4E9D-BFAC-811EAD9FF224" src="https://user-images.githubusercontent.com/32924396/139075397-ff584f2a-63c4-4a61-a389-78f0a57b6f23.png">

Hi Professor, here is the formula. In my understanding, after computing color(p + tr), each color channel will be multiplied by k_r/k_g/k_b. So what are a_r, a_g, a_b here? What is the relation between k and mat.reflection_color from the json file in Assignment 3?

**Comment by Sanainui** [comment]
@danielepanozzo Hi Professor, could you please clarify the notions?

**Comment by danielepanozzo** [comment]
a = (a_r,a_g,a_b) is an attenuation constant between 0 and 1. a_r corresponds to the attenuation of the red channel, and so on. k = (k_r,k_g,k_b) is explicitly defined in the pseudocode. Both a and k are explained in the page before (325).

**Comment by Sanainui** [comment]
> a = (a_r,a_g,a_b) is an attenuation constant between 0 and 1. a_r corresponds to the attenuation of the red channel, and so on. k = (k_r,k_g,k_b) is explicitly defined in the pseudocode. Both a and k are explained in the page before (325).

Ok, I just noticed that a has been defined earlier. Since the json file doesn't specify the value of a, so we can play around with it? In addition, I want to make sure if we want to implement Fresnel equations like the code above, the reflection color and refraction color in the json file will not be used, right?

**Comment by danielepanozzo** [comment]
Yes you can play around with all the parameters, not only a. Yes you do not have to use the ones in the json file.
