### ISSUE TITLE
Sensor, Camera, and Pixel Grid

### ISSUE THREAD

**Issue by yanhao-li** [danielepanozzo/cg#4]
Hi Professor,

I'm confused with those terminologies: `sensor`, `camera`, `pixel grid`

in Assignment 3 Exercise 1
![image](https://user-images.githubusercontent.com/12378652/95666244-ce6ede80-0b25-11eb-8dbf-8ad3026ff47e.png)
According to the README,
>The field of view of a perspective camera represents the angle formed between the center of the camera and the sensor (aka the pixel grid through which rays are shot)

so I'm assuming 1 is the `camera`, 2 is `sensor` == `pixel grid` 

but in the [code annotation](https://github.com/danielepanozzo/cg/blob/master/Assignment_3/src/main.cpp#L224-L226), you are saying 
>The pixel grid through which we shoot rays is at a distance 'focal_length' from the sensor

That makes `sensor` and `pixel grid` sounds like different things, and in the above image, 1 will be `camera` == `sensor`, 2 will be the `pixel grid`.

I understand there is a sensor inside the camera, so when we are talking about `camera`, are we seeing it as a point, or a w*h sensor pixel grid?

Furthermore, what these three terminologies `sensor`, `camera`, `pixel grid` usually mean in computer graphic, and what's their relationship? 

Would you mind clarifying a little bit more? 

Really appreciate that!

**Comment by danielepanozzo** [comment]
Hi,

I will discuss it today during class. The comment in the code is indeed confusing, your first interpretation is the correct one.

**Comment by yanhao-li** [comment]
@danielepanozzo Thank you!
