### ISSUE TITLE
grid position problem

### ISSUE THREAD

**Issue by enrui-shi** [danielepanozzo/cg#40]
In line 227 the code init the grid at [x,y,-5] and the camera is at [0,0,5]. But the z value of all spheres is 1 or -1. Is that means that all sphere is between the camera and the grid?

**Comment by danielepanozzo** [comment]
Yes, the grid z location corresponds to the z plane which is in focus. It can be anywhere in the scene (the fact that we use -focal_length in the assignment is arbitrary.)
