### ISSUE TITLE
How long should the dragon take

### ISSUE THREAD

**Issue by dfeldan** [danielepanozzo/cg#41]
I finished implementing the AABBtree and when I tried it with the bunny it went very fast (not instantaneous, but a matter of seconds).
I then went on to try with the dragon, and 20 minutes later, it is still building the tree and hasn't even started rendering the scene. Is this normal/ To be expected? What is a reasonable time that the dragon should take with our accelerated data structure?

**Comment by yl8209** [comment]
It took my top-down approach implementation 2-3 seconds to construct the tree for dragon. Using iteration instead of recursive call may give you better performance.

**Comment by danielepanozzo** [comment]
Make sure you are compiling in release. If this still does not fix the issue, you would have to time your code with a profiler to see where the time is spent. In which OS are you working on?

**Comment by dfeldan** [comment]
I figured out the issue. In recursive function I was passing my vector of triangles not as a pointer so it was copying all the triangles at every recursive step. Now the creation of the AABBTree takes like 20-30 seconds and then the raytracing is very fast afterwards.
