### ISSUE TITLE
Clarification for the tasks required for assignment 4

### ISSUE THREAD

**Issue by khandu-utkarsh** [danielepanozzo/cg#42]
I wanted to clarify that for assignment 4 (mandatory one), we only need to implement the following five tasks:

1. Intersection between triangles and mesh
2. Ray tracing of triangle and mesh
3. Intersection of a ray and bounding box
4. Implementation of AABB
5. Intersection of ray and mesh using AABB

There are many TODOs in the code for assignment 4, like depth of field, the intersection of sphere and parallelogram, shadow rays, and specular contribution reflected ray and refracted ray, find the nearest and is light visible function.

We don't need to add all these stuff like shadows, reflection, etc for assignment 4? There are only supposed to be for assignment 3, right?

**Comment by danielepanozzo** [comment]
Yes that's correct.
