### ISSUE TITLE
Centroid of bounding box

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#44]
I have found this method in Eigen that says it produces the centroid of the bounding box:  EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE().

The documentation is [here]( https://eigen.tuxfamily.org/dox/classEigen_1_1AlignedBox.html#ab4950605c14c530c2d56c75f0e253d10).

However, I'm unsure how to actually use it.  I think the centroid of the box should be a Vector3d, since it's just a point, but when I try to call it I get 
error: no member named 'EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE' in 'Eigen::AlignedBox<double, 3>'

How do I get this value?

**Comment by Huangzizhou** [comment]
The source code is [here](https://eigen.tuxfamily.org/dox/AlignedBox_8h_source.html). 

`EIGEN_DEVICE_FUNC inline const EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(VectorTypeSum, RealScalar, quotient)
center() const
 { return (m_min+m_max)/RealScalar(2); }`

The name of this function is `center()`, not `EIGEN_EXPR_BINARYOP_SCALAR_RETURN_TYPE(VectorTypeSum, RealScalar, quotient)`. This is probably a bug in the Eigen documentation?

**Comment by jessberg** [comment]
Thanks!
