### ISSUE TITLE
how to use AlignedBox3d?

### ISSUE THREAD

**Issue by Sanainui** [danielepanozzo/cg#45]
How to access the corners of a box?

**Comment by Huangzizhou** [comment]
Please make use of the documentation of Eigen [here](https://eigen.tuxfamily.org/dox/classEigen_1_1AlignedBox.html#a09619d632dd6979e9d09738493221d55). There's a function called corner().

**Comment by Sanainui** [comment]
@Huangzizhou Hi Zizhou, thanks for your reply. I tried to understand the document but I still get stuck: when we call box.corner(), what is the parameter inside? Apart from corner(), are we expected to use other methods for this data structure?

**Comment by Sanainui** [comment]
Okay, I have figured it out by myself. We need to call sth like box.corner(AlignedBox3d::BottomLeftFloor)

**Comment by Huangzizhou** [comment]
You can use `box.corner(AlignedBox3d::CornerType::TopRightCeil)` and `box.corner(AlignedBox3d::CornerType::BottomLeftFloor)` to get the top-right corner and the bottom-left corner. You can use any function of `AlignedBox3d` as you want.
