### ISSUE TITLE
Assignment 4 

### ISSUE THREAD

**Issue by BlakeHan01** [danielepanozzo/cg#46]
If we only implement the 5 tasks from issue #42, then we can't render the buddy and the dragon. Is that correct?

**Comment by danielepanozzo** [comment]
Why not?

**Comment by BlakeHan01** [comment]
Because after I finished mesh intersect, intersect triangle, and intersect box, the image I got is still empty, so I'm wondering if I'm missing some parts.

**Comment by danielepanozzo** [comment]
Every individual component should be tested in isolation (writing unit tests, or experimenting on simple scenes) to make sure that it is correct. It is likely that you have a bug in one of the parts and that's the reason why it does not work.

My recommendation was to first implement only the ray triangle intersection (which is similar to ray parallelogram) and make sure that the raytracer is able to render the bunny (and maybe a simpler scene with just one triangle). Only after this works, I recommend to try to accelerate this procedure using the AABB tree.

**Comment by BlakeHan01** [comment]
Thank you!
