### ISSUE TITLE
Submission of the animation in Assignment 3

### ISSUE THREAD

**Issue by FrankCCCCCC** [danielepanozzo/cg#47]
Dear professor or assistants,

I'm sorry to ask this question so late.  I want to know since it is a little difficult to add gif animation into latex, so for the result of Ex.5, can I put the gif into the zip file as a part of my report? Since I don‘t know whether you will rate the animation by running my code, or mainly by viewing the report, so I think I need to explain the missing part of my report.

-Zhiliang

**Comment by Huangzizhou** [comment]
Please put the gif and pictures in the report (or in the folder if you cannot put gif in the report). The grading is based on both your report and your code, we will run your code and view your report.

**Comment by FrankCCCCCC** [comment]
> Please put the gif and pictures in the report (or in the folder if you cannot put gif in the report). The grading is based on both your report and your code, we will run your code and view your report.

Yes I did that, there is gif in my submission. Thank you for your reply.
