### ISSUE TITLE
Some confusion for Assignment 5

### ISSUE THREAD

**Issue by Nero5023** [danielepanozzo/cg#49]
Dear Professor:

I have some confusion for Assignment 5:

1. Why the smaller the z value the closer to us it is?
2. Should we load the entire scene with materials, lights, and objects like Assignment 4 or just load the `xxx.off` obj?
3. I also see the `xxx.obj` files in `data` folder, is any start code to load them?

Thanks

**Comment by danielepanozzo** [comment]
1. No reason, it is an arbitrary choice. You can change it if you like.
2. As you prefer. You will need light, camera, and materials also in this assignment, but it is fine to hardcode them if you prefer.
3. You can use the same code used in the previous assignments to load the off file. The two .obj files in the data folder are there by accident, they are not needed for this assignment. If you want to use them to debug your code, you can convert them from obj to off using meshlab. (You just load them in meshlab and export them as off).
