### ISSUE TITLE
Calculating Diffuse and Specular Shading

### ISSUE THREAD

**Issue by allenZhangPersonal** [danielepanozzo/cg#51]
Just a confusion on assignment 5. It seems that in the updated document we should calculate the shading components in the fragment shader. Does this mean that we interpolate the normal in the vertex shader and use the normal in the fragment shader to calculate the color? I was calculating the color in the vertex shader and it seems that i can interpolate the normal instead and calculate the color in the fragment shader.

**Comment by Huangzizhou** [comment]
The professor mentioned in another [issue.](https://github.com/danielepanozzo/cg/issues/50)

> The assignment is asking to do the computation of the color in the vertex shader, and then interpolate it in the triangle. This is easier. In flat shading, all 3 vertices use the same normal (i.e. the normal of the triangle), for per-vertex shading, each vertex has its own normal. The fragment shader directly interpolates the color.

You don't need to interpolate normals in the vertex shader, instead, you specify `VertexAttributes::normal` before calling `rasterize_triangles`, then the normals are interpolated in `VertexAttributes::interpolate` in `raster.cpp`.

**Comment by khandu-utkarsh** [comment]
I too have doubts regarding the diffusive and specular shading implementation required in Exercise 2.

For implementing diffuse shading, we require: Normal, Intersection point and a light source, right?  I suppose in this case intersection point will be a vertex as we can computing color for each vertex. Normal can be computed as mentioned and we can assume the position of a light source. During the call to rasterization, fragment shader can use the interpolated value of the color.
Can you please confirm if I am correctly approaching the diffuse shading part?

For specular shading, we need normal, light source position and camera/view position. What should be the camera position in our case? It is mentioned that camera space is same as canonical space, so should camera position be at (0,0,0)?
If yes, then I think some of the vertices will be behind the camera, I can see vertices in the bunny to be having both positive and negative z coordinate.

Besides, does the fragment shader have only one responsibility, that is using the interpolated vertex attributes of that pixel and extracting color information out of it and creating a fragment_attributes object. If yes, why it is not done in blending shader?
What is the need of this extra shader function?

**Comment by danielepanozzo** [comment]
Yes for the diffuse shading part.

For specular, you need to decide in which reference system you want to do the shading computation. If you do it in camera reference system then the camera position will be indeed the origin. My suggestion is however to do it in world coordinates, so that you do not have to apply any transformation to the light position.

In this case the fragment shader will indeed just pass along the interpolated color. The blending shader is useful for other tests, for example the depth test as we discussed in class. this cannot be done in the fragment shader as it does not have access to the framebuffer.
