### ISSUE TITLE
Adding wireframe over flat shading in Exercise 2 Assignment 5

### ISSUE THREAD

**Issue by khandu-utkarsh** [danielepanozzo/cg#52]
While rendering flat shading, we used the normal at of the triangle as the normal of the vertex. Now, if we have to add wireframe on top of it, every edge that is shared between multiple triangles will have two normals? Which normal to choose in such cases?
Should be render edges twice both the times having different normals?

**Comment by happydl** [comment]
I think perhaps we don't need normals while rendering wireframes? I think a convenient way to achieve the result is to use a second pass but I don't know if this is the expected method.

**Comment by danielepanozzo** [comment]
You do not need normals to render the wireframe it is sufficient to render it with a fixed color. However, if you want, you can also do the shading for the wireframe, in that case you can use the per-vertex normals and they will be the same independently on which side of the edge you are.

**Comment by khandu-utkarsh** [comment]
Thanks professor! I got your point.

I added wireframe over the flat shading, but in my case, there are certain pixels missing. I believe this is because of the z buffer thing. I am attaching my rendered image for your reference.

My first approach was to reset the z buffer before rendering the wireframe one the flat shaded image. But I think that won't help because it might render wireframe for some internal trial.

My next idea was to reset the depth for every i and j in the FrameBufferAttributes buffer. But it will loose the existing information?

Can I get some hints on how to add wireframe over flat shaded bunny?
<img width="479" alt="Screen Shot 2021-11-15 at 2 17 13 AM" src="https://user-images.githubusercontent.com/60479858/141740432-b7732fe7-def2-4567-be79-713e648fad58.png">

**Comment by Huangzizhou** [comment]
Did you put the `rasterize_lines` before `rasterize_triangles`? In my case, if `rasterize_lines` is called before `rasterize_triangles`, this phenomenon happens; if `rasterize_lines` is called after `rasterize_triangles`, it goes away.

**Comment by khandu-utkarsh** [comment]
I am calling rasterize_lines after rasterize_triangles.

Also I am calling same line multiple times, as the same edge occur in more than one triangle. Can that be possible source of error?
Because this approach works fine while rendering just wireframe (part a exercise b) as no depth check is used there.

**Comment by Huangzizhou** [comment]
It should be fine to render repeated lines, but indeed you need to deal with the z-fighting. Originally, one should update the FrameBufferAttributes only if the new point is closer. However, you can define a special blending shader for the lines so that the FrameBufferAttributes get updated as long as `new_dist < old_dist + eps`, where `eps` is a small enough positive number.

**Comment by khandu-utkarsh** [comment]
I get you, and I think I wrongly communicated my thoughts.

I will try with using this eps value and check


For rendering just the wireframe part (part a), we don't need to deal with z-buffer.
I tried it both with and without z-buffer and it seems like the image available in the exercise description is generated by not using z-buffer. Am I correct?

**Comment by Huangzizhou** [comment]
Yes, it's the same for the wireframe part.

**Comment by jessberg** [comment]
That does not make sense to me;  the wireframe by itself shows the back side of the bunny.  Then if you do wireframe after flat shading, and don't take z-buffer things into account, the entire bunny wireframe, including wires "behind" the flat shading, shows up.  How else do you get the back of the bunny to not show up?

**Comment by jessberg** [comment]
Just in case the other student still has this problem - I had the same issue, and I solved it by thickening the width of the line to 1.  If the line is too thin, it breaks up into small fragments.

**Comment by Sanainui** [comment]
I also have the same issue here: some portion of the wireframe is missing over the flat-shaded bunny. I tried Zizhou's advice: in the _blendingshader_, I check **_fa.position[2] < previous.depth + 0.001_** to avoid z-fighting, but this is good only when the thickness is set to be above 0.5. (Pic attached when thickness = 0.5). Is this desirable or I need to do more?
![triangle](https://user-images.githubusercontent.com/32924396/142137913-61d59b85-bfde-4549-b0a2-efdef6746efa.png)

**Comment by danielepanozzo** [comment]
How does it look with thickness = 1?

**Comment by Sanainui** [comment]
Hi Professor, this is the pic when thickness = 1.
![triangle](https://user-images.githubusercontent.com/32924396/142141408-e72d08fa-acbd-402e-83ef-f7012789632d.png)

**Comment by danielepanozzo** [comment]
This is fine, the problem was indeed the thickness was too small, some pixels were dropped as their center was not sufficiently close to the line.

**Comment by Sanainui** [comment]
thank you Professor

**Comment by khandu-utkarsh** [comment]
It is working for me now. I tried the Zizhou's suggestion and set the pixel width to more than 0.5 as mentioned by Sanainui 
It is working for me as well.

Thanks all for your help!
