### ISSUE TITLE
Issue with bunny size

### ISSUE THREAD

**Issue by oliverzlu** [danielepanozzo/cg#54]
It says that we are supposed to be loading the same scenes used in Assignment 4, but the bunny.off provided in Assignment 5 is a lot smaller than the bunny.off provided in Assignment 4. Should we be using the bunny.off from Assignment 4?

**Comment by Huangzizhou** [comment]
It's fine to use either one, but it's better to make the model fit the scene, by tuning parameters or the model size, so that it can be seen clearly.

**Comment by oliverzlu** [comment]
OK, thanks!
