### ISSUE TITLE
Space Transformations Questions

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#55]
I understand that in order to do part 3, we need 3 transformations:  from object space to world space, world space to camera space, and camera space to canonical view volume.  However, I am confused as to how these are defined in the code.  Should world space origins/xyz vectors be defined in the uniform in terms of the object space?  Is camera space defined as the camera as the origin?  How do we define x, y, and z then?

**Comment by danielepanozzo** [comment]
This is difficult to discuss online, I recommend to join one of the office hours.
