### ISSUE TITLE
Gaze direction and view-up vector

### ISSUE THREAD

**Issue by DebraChait** [danielepanozzo/cg#59]
For translation, how do we find the gaze direction and view-up vector? We are not given the direction that the camera is pointing in, only its position.

**Comment by Huangzizhou** [comment]
You need to specify those camera parameters to make sure that the object is properly located inside the view. Following the assignment 3 and 4, you can specify the two directions based on this figure.
![fov](https://user-images.githubusercontent.com/41658484/142269438-1302a790-09e4-441e-855d-79dbef10a1c4.png)

**Comment by DebraChait** [comment]
I thought that in this picture, we are given the angle and the length f, and we compute the height h. How do we compute the gaze direction and view-up vector from here?

**Comment by Huangzizhou** [comment]
The gaze direction is the direction that the camera is looking at, i.e. (0,0,-1). The view-up direction is the direction of y-axis of the screen space, which is (0,1,0) in the figure.

**Comment by DebraChait** [comment]
Will it always be (0, 0, -1) for gaze direction and (0, 1, 0) for the view-up in our assignment, or are we supposed to somehow get this information from the angle and the camera position?

**Comment by Huangzizhou** [comment]
You don't need to compute these two directions based on the model, you can just assign (0,0,-1) and (0,1,0) in the code.
