### ISSUE TITLE
Possible Typo on Notes 5?

### ISSUE THREAD

**Issue by yanhao-li** [danielepanozzo/cg#6]
On [Keynote 05 - Ray Tracing](https://www.icloud.com/keynote/0Xt7leP_xqOA9pEE24U9-q5vg#05_-_Ray_Tracing)
Slide 26 - Ideal Reflections

For what the image shows
![image](https://user-images.githubusercontent.com/12378652/96265783-e3b79300-0f93-11eb-9f5d-29025b9c4cac.png)

Should the formula to calculate `r` be `r=d-2(d•n)n`, instead of `r=d+2(d•n)n`? 

since the project of `d` is pointing to the opposite direction from n, the scalar will be negative. Will the result of `2(d•n)n` a vector pointing down?

**Comment by danielepanozzo** [comment]
Thanks for spotting the typo, fixed!
