### ISSUE TITLE
Additional Header File

### ISSUE THREAD

**Issue by yaozcoderepo** [danielepanozzo/cg#63]
I think that I need two more additional header files in my main.cpp source code, which are
1. #include <fstream> (used for reading bunny.off file)
2.#include <Eigen/Geometry> (otherwise when I performed cross product on two Eigen::Vector3f, the compiler report link error)
Is including these two headers allowed?

**Comment by danielepanozzo** [comment]
2 is definitely fine, it is part of Eigen. For 1, you forgot to write the name of the header file.

**Comment by yaozcoderepo** [comment]
Oh sorry for that. For 1, can I #include fstream to read bunny.off file. (it turns out that fstream inside <> would disappear after posting on Issues.)
