### ISSUE TITLE
question about the transformation to canonical space

### ISSUE THREAD

**Issue by happydl** [danielepanozzo/cg#66]
I would like to know why we perform the final step, the division in the rasterization procedure rather than in the vertex shader.
Some answers say it's for the convenience of clipping, but I don't see the difference between clipping before or after the division.

**Comment by danielepanozzo** [comment]
It does not make any difference for our software rasterizer --- in our case it can be also done in the vertex shader as you suggest. In the OpenGL standard, it is done in the interpolation function. I don't exactly know why this is the case, it is likely making (or was making historically) an hardware implementation easier. In case you manage to track it down and you find an answer please share it here.

**Comment by happydl** [comment]
https://computergraphics.stackexchange.com/questions/5922/why-does-opengl-perform-clipping-in-clip-coordinates/5924
The point in this answer seems to make sense. a point (0,0,0,1) would make the w=0 after perspective projection.
