### ISSUE TITLE
Compiling issues for Assignment_6

### ISSUE THREAD

**Issue by rzc1731** [danielepanozzo/cg#68]
I have some issues when I try to compile Assignment 6.
I am working with Visual Studio 2019 on Windows 10.  When I run `cmake -DCMAKE_BUILD_TYPE=Debug ..`\ , it succeeded but showing that `Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`. Also, some tests failed.
The following file shows the full message after I ran cmake.
[Trace.txt](https://github.com/danielepanozzo/cg/files/7573802/Trace.txt)
I can still build solution successfully in Visual Studio, but I don't know if the missing part will cause problems later.

**Comment by danielepanozzo** [comment]
Can you launch the compiled application and do you see the triangle? If you see the triangle and the triangle changes as you left click on the window, then it should be fine to ignore the cmake warning.

**Comment by rzc1731** [comment]
I was worrying about the compiling because when I tried to run it from Visual Studio directly, it says `Unable to start the program`.  But it seems that the problem comes from the compiled application having a different name from the project folder. I can launch it in the debug folder and see the triangle changes. Thanks a lot for your help.
