### ISSUE TITLE
Every letter/click results in two callbacks

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#69]
I am trying to start work on assignment 6, but I am getting a weird error, so I was wondering if anyone else had this problem.  Every time I enter a letter or click, it is recorded twice, and results in two callbacks.  I have tested this on various letters and also on the mouse click.  So, for example, if I press the i button once, it always tells me that I have entered the key_pressed callback twice.  Similarly, every time I click, it says I have clicked on the same position twice.  How can I get it to only register one click/button press?

It also has the repeat variable set to 0 each time, and clicks set to 1 each time, so I don't think I can differentiate with that.

**Comment by danielepanozzo** [comment]
This is the correct behavior. There is an event for pressing a key/mouse button down and one for when it is released. You can use the other parameters in the callback to distinguish between the two types of events. You can take a look at the documentation of SDL to see what are the meaning of the other parameters.
