### ISSUE TITLE
A reference value to measure the render speed of the Assigenment 4

### ISSUE THREAD

**Issue by FrankCCCCCC** [danielepanozzo/cg#70]
Due to the feedback of my Assignment4, I want to know what time is considered as a fast render. I did finish my local render in several seconds but points were deducted.

**Comment by Huangzizhou** [comment]
Could you please provide your name or netid so that we can double check the performance?

**Comment by arvigj** [comment]
Please send us an email with this

**Comment by FrankCCCCCC** [comment]
> Could you please provide your name so that we can double check the performance?

Sure, my netid: zc2244

**Comment by Huangzizhou** [comment]
Resolved through emails.
