### ISSUE TITLE
Scaling/Rotation in Vertex Shader

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#77]
I am having trouble understanding how/why one would achieve having all the rotation and scaling within the vertex shader.  If both transformations are there, then we will use the original vertices for the point inside triangle test when the user clicks.  Then if the user tries to do a rotation and then a translation, you may not register that the user clicked on the rotated part of the triangle, because you're using the original vertices.  Theoretically you could rotate the relevant triangle before the point in polygon test, but that doesn't seem to save any work to me;  that's essentially the same cost as saving the rotated vertices outside of the vertex shader.  Am I missing something?

The same I believe applies to scaling - if I scale in the vertex shader, but not actually in my vertices, and then when I click a region that used to not be a part of the triangle but now is, I will not register that the user has clicked on a triangle.

**Comment by HerlinHe** [comment]
So, professor, do you mean we need to store a list of transform matrices for each triangle somewhere (like the uniform)? Since we are not supposed to change the original position.

**Comment by danielepanozzo** [comment]
For every object in your scene (in your case for every triangle), you should store its transformation. Before drawing each triangle, you upload the transformation in a uniform and you can use it in the vertex shader.

You can also store another transformation, which is temporary and only use to preview the current transformation as the mouse moves around.

This does not save any work in our software rasterizer, but simulates what you would do with OpenGL or any other API: in more realistic cases your objects will be made of many triangles (and not just one) and so this will allow you to take advantage of the GPU to apply the same transformation to all the triangles forming an object.
