### ISSUE TITLE
Unsigned int as the loop variant in the raster.cpp

### ISSUE THREAD

**Issue by greenson** [danielepanozzo/cg#8]
Hi Professor,  

I was doing assignment 6 and have been playing around with as many corner cases as possible. I spotted that using the `unsigned int` type as the loop variants in the `rasterize_triangle()` and `rasterize_line()` methods of the raster.cpp may result in an extremely long loop that seems as if it will never end.  
![image](https://user-images.githubusercontent.com/17645845/102680240-85ba4e00-4184-11eb-9686-618dff48f3d0.png)  
This issue happens when `ux` or `uy` is an negative number, i.e. the triangle to be drawn is below or on the left outside of the view space. Since `i` and `j` are unsigned integers while `ux` and `uy` are signed integers, the comparison between `i` and `ux` or  `j` and `uy` would make the compiler convert both `ux` or `uy` into unsigned integers as well. Therefore, if `ux` or `uy` are negative integers, they would be converted to some very large unsigned integers which causes the problem like this.  
![image](https://user-images.githubusercontent.com/17645845/102680249-9bc80e80-4184-11eb-8fff-5417de1c1288.png)  
  
**Possible fix**:  initialize the loop variants `i` and `j` as normal int.

**Comment by danielepanozzo** [comment]
This should be prevented by the clamping that happens a few lines above:

		// Clamp to framebuffer
		lx = std::min(std::max(lx,int(0)),int(frameBuffer.rows()-1));
		ly = std::min(std::max(ly,int(0)),int(frameBuffer.cols()-1));
		ux = std::min(std::max(ux,int(0)),int(frameBuffer.rows()-1));
		uy = std::min(std::max(uy,int(0)),int(frameBuffer.cols()-1));

How can ux and uy to be negative? Did you change some other parts of the rasterizer?

**Comment by greenson** [comment]
> This should be prevented by the clamping that happens a few lines above:
> 
> ```
> 	// Clamp to framebuffer
> 	lx = std::min(std::max(lx,int(0)),int(frameBuffer.rows()-1));
> 	ly = std::min(std::max(ly,int(0)),int(frameBuffer.cols()-1));
> 	ux = std::min(std::max(ux,int(0)),int(frameBuffer.rows()-1));
> 	uy = std::min(std::max(uy,int(0)),int(frameBuffer.cols()-1));
> ```
> 
> How can ux and uy to be negative? Did you change some other parts of the rasterizer?

It turned out that I was using the old version of the raster.cpp which I cloned at the beginning of this semester:
```C++
// Clamp to framebuffer
lx = std::max(lx,int(0));
ly = std::max(ly,int(0));
ux = std::min(ux,int(frameBuffer.rows()-1));
uy = std::min(uy,int(frameBuffer.cols()-1)); 
```
It makes sense now, thank you!
