### ISSUE TITLE
Assignment 6 Best Practices Question

### ISSUE THREAD

**Issue by dfeldan** [danielepanozzo/cg#80]
For assignment 6 I am doing my own project, but I have some questions about best practices in C++
Background info:  I am making a simple particle physics simulator. I have an abstract Box class which has a position, color, and abstract update method. I plan on storing these boxes in some sort of 2d grid. 
1) I want to create basically different types of boxes. For example, stone has a grey color and when update is called, it will not move. Sand is yellow and when update is called it will attempt to move 1 row down in the grid. I can have many different types of sand, and the only difference between different particles of sand would be their position. Right now, for each type of box I am making a subclass which inherits box, and then has a constant color and an implemented update method, but for some reason I keep thinking there is a better way to do it. Something like don't make Box abstract and make the update function a function pointer instead. In Then just make like 2 instances of it and store them in a map. And have a builder class return a copy of the type of box you want. 

2)  For context my grid will be around 500x 500 points. I want to make my grid a sparse grid, because most points in the grid will not have blocks in them. It is also important that I be able to iterate over the items in the grid, and fast look up times (since sometimes when update is called, each block will need to access multiple cells around it). For now, I am using a sorted map, keyed by the position in the grid [(0,0),(0,1)...] but doing it this way means that each look up is o(log(n)). I am also thinking about making a 2D matrix of Box pointers, and each entry in the array which doesn't currently have a box in them be a null_ptr, but dealing with null_ptrs can get messy

I have ways to get around these problems, I just want to make sure that my thought processes isn't incorrect because of my limited knowledge of c++

**Comment by danielepanozzo** [comment]
1. Inheritance sounds like the way to go to me. The overhead of virtual methods over function is negligible.
2. 500x500 is not much. I think a dense matrix would be simpler and faster, as it will give you O(1) access for navigation.
