### ISSUE TITLE
Assignment 6, Ex4

### ISSUE THREAD

**Issue by Sanainui** [danielepanozzo/cg#81]
How can we move all space transformations into the vertex shader without modifying the raster? The current vertex shader processes a single vertex without knowing their position information inside the vector, but we want three specific vertices in the vector to be modified.

**Comment by Huangzizhou** [comment]
You can add additional information to the VertexAttributes to keep track of which triangle that vertex belongs to.

**Comment by Sanainui** [comment]
If I understand correctly, the vertex shader should directly modify the vertices vector. So we need to put vertices vector in the uniform?

**Comment by danielepanozzo** [comment]
I think this is a similar issue as https://github.com/danielepanozzo/cg/issues/77, let me know if there is still confusion on how to do this.

**Comment by Sanainui** [comment]
@danielepanozzo Hi Professor, I do have some questions. If we do all transformations in the vertex shader, we also need to update the position in the vertices vector, right? Suppose vertices vector is stored in uniform, then we need to modify uniform. In this case, we want to change the vertexshader function to program.VertexShader = [](VertexAttributes& va, UniformAttributes& uniform) without constant.

**Comment by Sanainui** [comment]
I think I understand what we are required to do by reading #77. I have one remaining question: I apply transformation in computing barycenter and my picking function since they need the up-to-date information of position. Is this acceptable?

**Comment by Huangzizhou** [comment]
You don't need to modify anything inside the vertex shader, the transformations are always stored in a matrix and the vertex positions outside are unchanged, then you apply that matrix inside the vertex shader.

Yes, you do need to apply the transformations when you select a triangle with your mouse or compute the barycenter.
