### ISSUE TITLE
Compiling issue for Assignment 6: error: unknown type name 'nullable'

### ISSUE THREAD

**Issue by zhiqiiiiiii** [danielepanozzo/cg#83]
Hi, did anyone encounter the same error when compiling assignment 6?
My environment settings are as follows: macOS 11.6, GNU 11.2.0, Xcode 13.1.

**Comment by danielepanozzo** [comment]
Can you post the entire compilation log?

**Comment by zhiqiiiiiii** [comment]
I switched to appleclang and problem solved. Thanks!
