### ISSUE TITLE
Assignment 6 Ex.6: what does linear interpolation do here?

### ISSUE THREAD

**Issue by Sanainui** [danielepanozzo/cg#84]
Suppose I want to keyframe the position of a triangle.  My current idea is that I have one triangle p selected, so p's transformation matrix should be stored in my frame vector (p has 3 vertices with identical matrix, so I only need to store one). After dragging p into p', its corresponding transformation matrix will be changed. So I again store this matrix. With two matrices, how can I do linear interpolation?

**Comment by danielepanozzo** [comment]
If you have 2 transformation matrices, you can interpolate them by doing linear interpolation on each one of their entries.

**Comment by DebraChait** [comment]
Do we need to allow linear interpolation for the movement of multiple triangles, or is movement over one triangle sufficient?

**Comment by danielepanozzo** [comment]
One triangle is sufficient.
