### ISSUE TITLE
A6: No available video source

### ISSUE THREAD

**Issue by oliverzlu** [danielepanozzo/cg#85]
My code compiles successfully, but I get the following error when I try running RasterViewer:

`error initializing SDL: no available video source`

Is there a suggested/recommended video source that I should use/download?

Or, is there usually not a problem with SDL not finding a video source?

Or, is there some particular way that we should be running RasterViewer?

**Comment by danielepanozzo** [comment]
This is strange, on which operating system are you compiling/running? Could you send the cmake and compilation log.

**Comment by oliverzlu** [comment]
I am compiling/running on Ubuntu 20.04.

I am not exactly sure what is the cmake and compilation log, let me know if I have attached something incorrect.

[CMakeLists.txt](https://github.com/danielepanozzo/cg/files/7705037/CMakeLists.txt)
[CMakeOutput.log](https://github.com/danielepanozzo/cg/files/7705040/CMakeOutput.log)

**Comment by danielepanozzo** [comment]
From the log it seems that you are using WSL on windows and running ubuntu in a virtual machine. This is not something we support, on windows, you should compile using visual studio 2019 or 2022.

**Comment by danielepanozzo** [comment]
(The problem is that certain version of WSL do not have access to an xserver and cannot open windows. I think this has been solved by Windows 11 but I did not test it yet)

**Comment by oliverzlu** [comment]
OK, I will try with VIsual Studio.

The problem seems to be resolved. Thanks!
