### ISSUE TITLE
Assignment6: fail to make with release mode

### ISSUE THREAD

**Issue by FrankCCCCCC** [danielepanozzo/cg#86]
I was using windows os and appling ` cmake -G "MinGW Makefiles" ..` to use **cmake** (with default release mode), it seemed successful and then I tried `make` and it returned error with 50% finished.
![1](https://user-images.githubusercontent.com/75361328/145752865-e05f4bb7-7eaa-487c-b9ac-7021c22c3430.png)

The relevant lines which is shown in the terminal is:

1. CMakeFiles\RasterViewer.dir\build.make:118(I copied from line 116-118): RasterViewer.exe: CMakeFiles/RasterViewer.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=C:\Users\ASUS\.vscode\cg-master\Assignment_6\build\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Linking CXX executable RasterViewer.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\RasterViewer.dir\link.txt --verbose=$(VERBOSE)

2. CMakeFiles\Makefile2:133: $(MAKE) $(MAKESILENT) -f CMakeFiles\RasterViewer.dir\build.make CMakeFiles/RasterViewer.dir/build

**Comment by danielepanozzo** [comment]
Please use visual studio 2019 or 2022 c++ compiler instead, the code has not been tested (and we cannot provide support) for mingw.

**Comment by FrankCCCCCC** [comment]
> Please use visual studio 2019 or 2022 c++ compiler instead, the code has not been tested (and we cannot provide support) for mingw.

Thank you professor, my code now works and I would like to share my experience here: now I use `cmake -G "Visual Studio 17 2022" ..` to generate VS project( of course I installed **Visual Studio** at first), then I open the **Visual Studio** to find the generated project file. Finally I make the .exe from **Visual Studio**. The RasterView.exe is generated, I can find it from `cd build\Debug ` , and this is what we need to see.
