### ISSUE TITLE
Scaling Proportion

### ISSUE THREAD

**Issue by yaozcoderepo** [danielepanozzo/cg#88]
In ex.2 and ex5, we are asked to scale up the primitive or entire scene by a certain percentage, say 10%. I wonder if this 10% is relative to its current size. If it is, this means that a line of length 1 would be of length 1.1 (1 * (1+10%) = 1.1) after being scaled up 10%, and would be 0.99 (1.1 * (1-10%) = 0.99) (**instead of 1**) after further being scaled down 10%. Thus, I want to make sure if this is what is intended.

**Comment by Huangzizhou** [comment]
Yes, you are right, this is how it should be.
