### ISSUE TITLE
Question on load obj

### ISSUE THREAD

**Issue by xiaotanker** [danielepanozzo/cg#9]
Does input obj file of  Assignment 1 contains all possilble types? 
Or just like the example input, which has only v and f?

**Comment by arvigj** [comment]
I don't understand your question. What do you mean by all possible types?

**Comment by xiaotanker** [comment]
in convex hull, the obj file we output has v and l.
and in points_in_polygon, the  input obj has v and f.
are we sopposed to handle these two types of input?
or just the example input.

**Comment by xiaotanker** [comment]
in other words, when grading assignment 1, does the input obj file only contains multiple lines of v followed by 1 line of f? just like the example input obj file?

**Comment by arvigj** [comment]
In my understanding these are two different assignments and you are explicitly given the inputs to both. In any case it's an optional assignment, so you can do whatever you want (handle the output of the first assignment in the second one, etc.). If this is not clear, please attend office hours.

**Comment by xiaotanker** [comment]
thank you
