### ISSUE TITLE
Assignment 6 Ex.6

### ISSUE THREAD

**Issue by yaozcoderepo** [danielepanozzo/cg#90]
I want to make sure if I understand Ex.6 correctly:
1. We should add one "keyframe" every time we press "K" button. We can add as many keyframes as we want. Say there are n keyframes (so "K" button is pressed n times). Let's denote them k_1, k_2, ..., k_n
2. For linear interpolation, once we pressed "A", shall we are supposed to linear-interpolate between each pair (k_1, k_2), (k_2, k_3), ..., (k_{n-1}, k_n}, right? Thus, for linear interpolation, the animation would go through all the intermediate keyframes.
3. For Bezier curve, the degree of the curve is determined by the number of keyframes (n), such that n keyframes imply (n-1) degree of Beizer curve, right? Thus, for Beizer curve, the animation would go through only the first keyframe (k_1) and the last keyframe (k_n) (the path of curve would be affected by k_2, k_3, ..., k_{n-1}, but not go through them).

**Comment by danielepanozzo** [comment]
Yes to all 3.
