### ISSUE TITLE
What to include in video?

### ISSUE THREAD

**Issue by jessberg** [danielepanozzo/cg#93]
For the video, how will it be graded?  What should we include in the video?  Just a demonstration of all the features?  Should we go into detail on how we implemented each of them?  If we changed some key bindings, should we include that in the video?

**Comment by danielepanozzo** [comment]
The quality of the video itself will not be graded. You should include a demo of you assignment 6 or final project, showing all the features that you implemented. If you changed the keybindings, please include the list in a separate text file.

**Comment by Sanainui** [comment]
For assignment 6, if I have orally introduced the changed keybindings in the video, should I still include the list in a separate text file?

**Comment by danielepanozzo** [comment]
Yes if you changed the keybindings please write it in a separate file.
