### ISSUE TITLE
Video Length

### ISSUE THREAD

**Issue by dfeldan** [danielepanozzo/cg#94]
How long is our video supposed to be?
Right now, I recorded myself and it took 10 minutes. I may be able to cut some time and make it a bit shorter, but my project has a lot of features and I do not know if I can significantly shorten the presentation.

**Comment by danielepanozzo** [comment]
3 minutes max. I suggest you upload two of them, one you can keep it longer where you showcase all features, the second should be a quick overview that is at most 3 minutes long.

**Comment by dfeldan** [comment]
Ok, thank you so much
