### ISSUE TITLE
Assignment 6, Ex.6: how to redraw frames within a for loop?

### ISSUE THREAD

**Issue by zhiqiiiiiii** [danielepanozzo/cg#95]
Hi, I'm trying to do animation by redrawing the linear interpolated frame within a for loop. So I set viewer.redraw_next = True in every iteration of the for loop as follows:

for every frame:
     operations to interpolate vertices between key frames;
     viewer.redraw_next = true;

However, it only updates the frame once at the end.

Any hints on how to do animation? Thanks!

**Comment by jessberg** [comment]
viewer.redraw_next=true only makes the frame buffer update once the current function has finished execution.  You need to have some sort of counter, like for a for loop, outside of the callback, and increment it within the callback, and set viewer.redraw_next=true while you believe the "loop" should still be executing.

**Comment by zhiqiiiiiii** [comment]
got it, thanks
