### ISSUE TITLE
In Assignment 6, Can we make small adjustment on how the User Interaction should work?

### ISSUE THREAD

**Issue by benno0810** [danielepanozzo/cg#96]
For example, in EX.1 we should first enter the Translation Mode then select triangles to move them.
The workflow should be like this if I am understanding it right:
#######################################
 (workflow 1) 
Step 1-> enter "o" 
Step 2-> drag triangle_1 to its newest position and rotate/scale 
Step 3-> drag triangle_2 to its newest position
...
Step Final->exit mode.
########################################

However, can it also be: ?
#####################################
 (workflow 2):
Step1-> enter "o"
Step2-> drag triangle_1 and/or rotate/scale
step3-> translation end selection reset
...
Step N-> enter "o"
Step N+1-> drag triangle_2 and/or rotate/scale
step N+2-> translation end selection reset
###################################

Workflow 2 is easier to implement and I think when there's a corner case (such as a triangle is scaling too small so that selection highlight is lost) forcing to only operate on one triangle each time can better trace the bug in developing and to reset when using this application...

**Comment by danielepanozzo** [comment]
The two workflows seems very similar to me, I do not understand why the second one is easier. If you prefer you can go with the second one. If you do please add a description of the chance (and why you had to do it) in a readme file.
