### ISSUE TITLE
Assignment 6: Can I remove the build folder this time?

### ISSUE THREAD

**Issue by FrankCCCCCC** [danielepanozzo/cg#97]
When I plan to zip everything and submit it, I find that my build file this time has almost 400MB. It may because I use Visual Studio this time.

I used to submit the whole folder before. Since this time it seems too big and the build work could be done again with reproducing the code from another computer, can I delete it?

**Comment by arvigj** [comment]
Yes.

**Comment by FrankCCCCCC** [comment]
> Yes.

Thanks
